# Generated by Django 3.2.7 on 2022-05-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='totaldomainqoutation',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.RemoveField(
            model_name='totaldomainqoutation',
            name='agricultureTotal',
        ),
        migrations.RemoveField(
            model_name='totaldomainqoutation',
            name='educationTotal',
        ),
        migrations.RemoveField(
            model_name='totaldomainqoutation',
            name='healthcareTotal',
        ),
        migrations.RemoveField(
            model_name='totaldomainqoutation',
            name='manufacturingTotal',
        ),
        migrations.RemoveField(
            model_name='totaldomainqoutation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='totaldomainqoutation',
            name='retailTotal',
        ),
        migrations.AddField(
            model_name='totaldomainqoutation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='totaldomainqoutation',
            name='fullName',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
