# Generated by Django 3.2.7 on 2022-05-09 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220509_0058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TotalDomainQoutation',
            new_name='Quotations',
        ),
    ]
