# Generated by Django 3.2.7 on 2022-05-05 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220505_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agriculturedomain',
            name='user',
        ),
        migrations.AddField(
            model_name='agriculturesignup',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.agriculturedomain'),
        ),
    ]
