# Generated by Django 3.2.7 on 2022-05-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_totaldomainqoutation_quotations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quotations',
        ),
    ]
