# Generated by Django 3.2.7 on 2022-05-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_quotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculturesignup',
            name='password',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='educationsignup',
            name='password',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='healthcaresignup',
            name='password',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingsignup',
            name='password',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='retailsignup',
            name='password',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
