# Generated by Django 3.2.7 on 2022-05-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220505_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculturedomain',
            name='isActive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
