# Generated by Django 3.2.7 on 2022-05-05 14:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_agriculturedomain_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('isOccupied', models.BooleanField(blank=True, default=False, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthcareDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('isOccupied', models.BooleanField(blank=True, default=False, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturingDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('isOccupied', models.BooleanField(blank=True, default=False, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetailDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('isOccupied', models.BooleanField(blank=True, default=False, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='agriculturesignup',
            name='isFree',
        ),
        migrations.RemoveField(
            model_name='educationsignup',
            name='isFree',
        ),
        migrations.RemoveField(
            model_name='healthcaresignup',
            name='isFree',
        ),
        migrations.RemoveField(
            model_name='manufacturingsignup',
            name='isFree',
        ),
        migrations.RemoveField(
            model_name='retailsignup',
            name='isFree',
        ),
        migrations.AddField(
            model_name='agriculturesignup',
            name='isActive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='educationsignup',
            name='account',
            field=models.CharField(blank=True, default='Free', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='educationsignup',
            name='isActive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcaresignup',
            name='account',
            field=models.CharField(blank=True, default='Free', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='healthcaresignup',
            name='isActive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingsignup',
            name='account',
            field=models.CharField(blank=True, default='Free', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingsignup',
            name='isActive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='retailsignup',
            name='account',
            field=models.CharField(blank=True, default='Free', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='retailsignup',
            name='isActive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='agriculturedomain',
            name='isActive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='agriculturesignup',
            name='account',
            field=models.CharField(blank=True, default='Free', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='educationsignup',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.educationdomain'),
        ),
        migrations.AddField(
            model_name='healthcaresignup',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.healthcaredomain'),
        ),
        migrations.AddField(
            model_name='manufacturingsignup',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.manufacturingdomain'),
        ),
        migrations.AddField(
            model_name='retailsignup',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.retaildomain'),
        ),
    ]
